#!/usr/bin/env node
// Regenerates src/data/demos.generated.ts from PUBLIC GitHub repos tagged `agentic-lab`.
// Usage: node scripts/sync-repos.mjs [owner]   (default owner: cuppibla)
// Requires the `gh` CLI authenticated locally, or GH_TOKEN set (in CI).

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const owner = process.argv[2] || 'cuppibla';
const INCLUDE_TOPIC = 'agentic-lab';

// GitHub repo topic -> concept id (see src/data/concepts.ts).
const TOPIC_TO_CONCEPT = {
  'agents-101': 'agents-101',
  agent: 'agents-101',
  adk: 'agents-101',
  'tool-use': 'tool-use',
  tools: 'tool-use',
  orchestration: 'orchestration',
  workflow: 'orchestration',
  'multi-agent': 'multi-agent',
  multiagent: 'multi-agent',
  a2a: 'a2a',
  'agent-registry': 'a2a',
  mcp: 'mcp',
  memory: 'memory',
  rag: 'rag',
  'browser-use': 'browser-use',
  browser: 'browser-use',
  'computer-use': 'browser-use',
  voice: 'voice',
  accessibility: 'accessibility',
  multimodal: 'multimodal',
  evals: 'evals',
  eval: 'evals',
  evaluation: 'evals',
  skills: 'skills',
  skill: 'skills',
};

const slugify = (name) =>
  name.toLowerCase().replace(/[_\s]+/g, '-').replace(/[^a-z0-9-]/g, '');

const raw = execSync(
  `gh repo list ${owner} --no-archived --limit 300 --json name,description,isPrivate,isFork,primaryLanguage,repositoryTopics,url,stargazerCount`,
  { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] },
);

const repos = JSON.parse(raw);

const demos = repos
  .filter((r) => !r.isPrivate && !r.isFork)
  .filter((r) => (r.repositoryTopics ?? []).some((t) => t.name === INCLUDE_TOPIC))
  .map((r) => {
    const topics = (r.repositoryTopics ?? []).map((t) => t.name);
    const concepts = [
      ...new Set(topics.map((t) => TOPIC_TO_CONCEPT[t]).filter(Boolean)),
    ];
    return {
      slug: slugify(r.name),
      title: r.name,
      oneliner: r.description || '',
      concepts: concepts.length ? concepts : ['agents-101'],
      stack: r.primaryLanguage?.name ? [r.primaryLanguage.name] : [],
      status: 'public',
      difficulty: 'intermediate',
      stars: r.stargazerCount || 0,
      repo: r.url,
    };
  })
  .sort((a, b) => b.stars - a.stars);

const header =
  '// AUTO-GENERATED by scripts/sync-repos.mjs — do not edit by hand.\n' +
  `// Public repos tagged \`${INCLUDE_TOPIC}\` on GitHub. Run \`npm run sync\` to refresh.\n` +
  "import type { Demo } from './demos';\n\nexport const demosGenerated: Demo[] = ";

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'src', 'data', 'demos.generated.ts');
writeFileSync(out, header + JSON.stringify(demos, null, 2) + ';\n');
console.log(`Wrote ${demos.length} demo(s) to ${out}`);
