// AUTO-GENERATED by scripts/sync-repos.mjs — do not edit by hand.
// Public repos tagged `agentic-lab` on GitHub. Run `npm run sync` to refresh.
import type { Demo } from './demos';

export const demosGenerated: Demo[] = [];
